# Generated by Django 5.0.4 on 2024-06-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('pes', models.CharField(blank=True, max_length=200)),
                ('desligamento', models.CharField(blank=True, max_length=10)),
                ('servico', models.CharField(blank=True, max_length=200)),
                ('postes', models.IntegerField(default=0)),
                ('apoio_linha_viva', models.CharField(blank=True, max_length=10)),
                ('concluir', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('encarregado', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
