# Generated by Django 5.0.4 on 2024-06-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_encarregado_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='encarregado',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='projeto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
